# Generated by Django 5.0.4 on 2024-04-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_preparation',
            field=models.TextField(blank=True, default='Kiritilmagan !', null=True, verbose_name='Taomning tayyorlanishi'),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_recipe',
            field=models.TextField(blank=True, default='Kiritilmagan !', null=True, verbose_name='Taomning retsepti'),
        ),
    ]
